name: tugas7_1
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.6
  get: 4.6.6
  flutter:
    sdk: flutter
  firebase_core: ^2.27.2
  firebase_storage: ^11.6.11
  cloud_firestore: ^4.15.10
  uuid: ^4.3.3
  intl: ^0.19.0
  cached_network_image: ^3.3.1
  image_picker: ^1.0.7
  flutter_native_splash: ^2.4.0
  flutter_local_notifications: ^17.0.0
  flutter_native_timezone: ^2.0.0
  get_storage: ^2.1.1
  flutter_screenutil: ^5.9.0

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

